default_language_version:
  python: python3.9
exclude: ^.*(\.lock|-lock\.json)$
repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.9
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=100
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-ast
      - id: check-byte-order-marker
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
      - id: check-merge-conflict
      - id: check-yaml
        args:
          - --unsafe
      - id: debug-statements
      - id: detect-private-key
      - id: requirements-txt-fixer
#      - id: no-commit-to-branch
  - repo: https://github.com/pycqa/isort
    rev: 5.11.2
    hooks:
      - id: isort
        name: isort (python)
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
      - id: bandit
        args: ["--exclude", "*/tests/*"]
# - repo: https://github.com/returntocorp/semgrep
#   rev: v0.97.0
#   hooks:
#     - id: semgrep
#       name: Semgrep Python
#       types: [python]
#       args: ['--config', 'https://semgrep.dev/p/python', '--error']
